export const experiences = [
  {
    id: 1,
    company: "Aligned Automation Pvt. Ltd · Full-time",
    logoAssetName: "aligned_logo",
    designation: "Solutions Engineer (Full-Stack Developer)",
    tenure: "April 2024 - Present",
    location: "Viman Nagar - Pune, Maharashtra, India - Onsite",
    isCurrent: true,
    description: [
      "Developed dynamic, responsive full-stack web applications using the MERN stack, resulting in a 30% improvement in site load time and a 20% increase in user engagement.",
      "Built and optimized responsive UI/UX features and reusable components in React.js, reducing development time by 15%.",
      "Managed complex application state using Redux and Context API, improving application performance and reducing state-related bugs by 25%.",
      "Developed and optimized MongoDB schemas, reducing database query times by 20%.",
      "Integrated RESTful APIs and third-party services to enhance application functionality.",
      "Ensured high application scalability and performance by implementing asynchronous programming techniques.",
      "Collaborated cross-functionally to troubleshoot complex issues, improve workflows, and maintain code quality.",
      "Maintained version control with Git, ensuring proper tracking of code changes.",
    ],
  },
  {
    id: 2,
    company: "Infoville Solutions India Pvt Ltd · Full-time",
    logoAssetName: "infoville_solutions",
    designation: "Jr. Software Developer",
    tenure: "March 2022 - March 2024",
    location: "Baner - Pune, Maharashtra, India - Remote",
    isCurrent: false,
    description: [
      "Developed and maintained user-facing features using React.js, ensuring a responsive, interactive user experience.",
      "Designed and implemented reusable UI components using React.js and Redux, resulting in 20% faster development cycles.",
      "Collaborated with UX/UI designers to convert design mockups into high quality frontend code.",
      "Optimized application performance by identifying and resolving bottlenecks in the React.js application.",
      "Ensured cross-browser compatibility and mobile responsiveness using CSS frameworks.",
      "Integrated RESTful APIs and third-party services to enhance application functionality.",
      "Implemented client-side routing using React Router for smooth transitions between different pages.",
      "Managed version control using Git and GitHub",
    ],
  },
  {
    id: 3,
    company: "Leadec Services Pvt Ltd (Client - FIAT) · Full-time",
    logoAssetName: "leadec",
    designation: "Jr. Maintenece Engineer",
    tenure: "Sept 2021 - March 2022",
    location: "Ranjangaon - Pune, Maharashtra, India - Onsite",
    isCurrent: false,
    description: [
      "Managed and maintained industrial machinery in Paint Shops, ABB Robots, conveyors, ensuring continuous operations.",
      "Proficient in spare parts management, preventing production delays, ensuring 99% availability.",
      "Skilled in handling industrial safety equipment, ensuring compliance with safety standards.",
      "Experienced in maintaining and troubleshooting key mechanical systems",
    ],
  },
  {
    id: 4,
    company: "Mutual Automotive Pvt. Ltd · Full-time",
    logoAssetName: "mutual_auto",
    designation: "Jr. Officer Maintenance",
    tenure: "June 2019 - August 2021",
    location: "Shikrapur - Pune, Maharashtra, India - Onsite",
    isCurrent: false,
    description: [
      "Shift In-Charge responsible for managing daily operations and ensuring timely troubleshooting.",
      "Maintained and repaired machinery in Paint Shop, including conveyors and robots.",
      "Expert in troubleshooting and maintaining B+M Robots and axis motors.",
      "Managed spare parts inventory to reduce maintenance downtime.",
    ],
  },
  {
    id: 5,
    company: "Radheya Machining Ltd · Full-time",
    logoAssetName: "radheya_machining",
    designation: "Graduate Engineering Trainee",
    tenure: "April 2017 - May 2019",
    location: "Sanswadi - Pune, Maharashtra, India - Onsite",
    isCurrent: false,
    description: [
      "Performed troubleshooting and breakdown maintenance on complex machinery.",
      "Maintained and repaired electrical and electronic systems reducing system failures.",
      "Managed and maintained PLC, VFD, CNC systems, and contactor logic.",
      "Diagnosed and repaired issues with CNC HMI screens and system components.",
    ],
  },
];
