export const experiences = [
  {
    id: 1,
    company: "Aligned Automation Pvt. Ltd · Full-time",
    logoAssetName: "aligned_logo",
    designation:
      "Senior Solutions Engineer (Full Stack | MERN Stack Developer)",
    tenure: "April 2024 - Present",
    location: "Pune, Maharashtra, India - Onsite",
    isCurrent: true,
    description: [
      "Promotion: Promoted from Solution Engineer to Senior Solutions Engineer in recognition of exceptional performance, leadership in full-stack development, and impactful contributions to high-priority projects.",
      "Developed dynamic, responsive full-stack web applications using the MERN stack (MongoDB, Express, React.js, Node.js), resulting in a 20% improvement in site load time and a 10% increase in user engagement.",
      "Managed complex application state management using Redux and Redux Toolkit, improving performance and reducing state-related bugs by 15%.",
      "Utilized Redis for caching and session management, significantly enhancing app performance and scalability under high traffic conditions and reduce database load.",
      "Learning the Kafka-based event-driven microservices to ensure asynchronous and scalable communication between services.",
      "Implemented MongoDB sharding and replica sets for high availability and scalability.",
      "Worked with MongoDB clustering for load balancing and improved performance in production environments.",
      "Optimized MongoDB schemas and queries, reducing database query time by 10%.",
      "Containerized applications using Docker, orchestrated multi-container setups using Kubernetes.",
      "Learned CI/CD pipelines using GitHub Actions/Jenkins for automated testing, building, and deployment.",
      "Integrated multiple payment gateways (e.g., Razorpay, PayPal) with secure transaction handling.",
      "Used Git/GitHub for version control and collaborated with team members using pull requests and code reviews.",
    ],
  },
  {
    id: 2,
    company: "Infoville Solutions India Pvt Ltd · Full-time",
    logoAssetName: "infoville_solutions",
    designation: "Jr. Software Developer",
    tenure: "March 2022 - March 2024",
    location: "Baner - Pune, Maharashtra, India - Remote",
    isCurrent: false,
    description: [
      "Developed and maintained responsive web applications using React.js, JavaScript (ES6+), and Context API for efficient state management",
      "Designed and implemented reusable UI components with React.js and Context API, reducing development cycles by 20%",
      "Collaborated closely with UX/UI designers to transform design mockups into high-quality, responsive frontend code that met user expectations",
      "Collaborated with cross-functional teams (Design, QA, and Backend) in Agile/Scrum development environments to deliver high-quality software.",
      "Implemented user authentication and authorization using JWT and bcrypt.js.",
      "Integrated RESTful APIs and third-party services to expand functionality and improve application features, enhancing user experience.",
      "Implemented client-side routing using React Router, ensuring smooth page transitions and improving the overall navigation flow",
      "Debugged and resolved bugs in production and staging environments using tools like Postman, Chrome DevTools, and server logs.",
    ],
  },
  {
    id: 3,
    company: "Leadec Services Pvt Ltd (Client - FIAT) · Full-time",
    logoAssetName: "leadec",
    designation: "Jr. Maintenece Engineer",
    tenure: "Sept 2021 - March 2022",
    location: "Ranjangaon - Pune, Maharashtra, India - Onsite",
    isCurrent: false,
    description: [
      "Managed and maintained industrial machinery in Paint Shops, ABB Robots, conveyors, ensuring continuous operations.",
      "Proficient in spare parts management, preventing production delays, ensuring 99% availability.",
      "Skilled in handling industrial safety equipment, ensuring compliance with safety standards.",
      "Experienced in maintaining and troubleshooting key mechanical systems",
    ],
  },
  {
    id: 4,
    company: "Mutual Automotive Pvt. Ltd · Full-time",
    logoAssetName: "mutual_auto",
    designation: "Jr. Officer Maintenance",
    tenure: "June 2019 - August 2021",
    location: "Shikrapur - Pune, Maharashtra, India - Onsite",
    isCurrent: false,
    description: [
      "Shift In-Charge responsible for managing daily operations and ensuring timely troubleshooting.",
      "Maintained and repaired machinery in Paint Shop, including conveyors and robots.",
      "Expert in troubleshooting and maintaining B+M Robots and axis motors.",
      "Managed spare parts inventory to reduce maintenance downtime.",
    ],
  },
  {
    id: 5,
    company: "Radheya Machining Ltd · Full-time",
    logoAssetName: "radheya_machining",
    designation: "Graduate Engineering Trainee",
    tenure: "April 2017 - May 2019",
    location: "Sanswadi - Pune, Maharashtra, India - Onsite",
    isCurrent: false,
    description: [
      "Performed troubleshooting and breakdown maintenance on complex machinery.",
      "Maintained and repaired electrical and electronic systems reducing system failures.",
      "Managed and maintained PLC, VFD, CNC systems, and contactor logic.",
      "Diagnosed and repaired issues with CNC HMI screens and system components.",
    ],
  },
];
